In [4]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd /content/gdrive/My Drive/thesis/deep-NMF/network_propogation
! git pull
# Settings -> Developer settings -> Personal access tokens -> Generate new token
# !git clone https://raminass:84cd7fa8518c54c125c98bb2dae23e5ad0531705@github.com/raminass/deep-NMF.git

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/My Drive/thesis/deep-NMF/network_propogation
Already up to date.


## importing

In [ ]:
%pip install mygene

In [ ]:
% pip install --upgrade scipy

In [1]:
from plotly.subplots import make_subplots
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy as sp
import math
import networkx as nx
from sklearn.linear_model import LinearRegression
import sklearn as sc
import plotly.graph_objects as go
# import mygene
import random
import joblib
import statsmodels.api as sm
import plotly.express as px
import os
from collections import defaultdict
%matplotlib inline
plt.style.use('seaborn-white')

%load_ext autoreload
%autoreload 2

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning:

pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.



In [2]:
# mg = mygene.MyGeneInfo()  # api to map genes code

# %%
# Global Variables
PROPAGATE_ALPHA = 0.9
PROPAGATE_ITERATIONS = 200
PROPAGATE_EPSILON = 10 ** (-4)
target = [
    1003,
    1000,
    1001,
    1002,
    1500,
    1499,
    1495,
    100506658,
    7122,
    7082,
    9414,
    27134,
]  # vascular protiens

target_names = [
    "Cadherin-5",
    "Cadherin-2",
    "Cadherin-3",
    "Cadherin-4",
    "Catenin delta 1",
    "Cateninβ  ",
    "α Catenin ",
    "Occludin",
    "Claudin-5",
    "ZO-1",
    "ZO-2",
    "ZO-3",
]

In [6]:
def read_network(network_filename):
    network = pd.read_table(network_filename, header=None, usecols=[0, 1, 2])
    return nx.from_pandas_edgelist(network, 0, 1, 2)


def generate_similarity_matrix(network):
    genes = sorted(network.nodes)
    matrix = nx.to_scipy_sparse_matrix(network, genes, weight=2)
    norm_matrix = sp.sparse.diags(1 / sp.sqrt(matrix.sum(0).A1), format="csr")
    matrix = norm_matrix * matrix * norm_matrix
    return PROPAGATE_ALPHA * matrix, genes


def propagate(seeds, matrix, gene_indexes, num_genes):
    F_t = np.zeros(num_genes)
    F_t[[gene_indexes[seed] for seed in seeds if seed in gene_indexes]] = 1
    Y = (1 - PROPAGATE_ALPHA) * F_t

    for _ in range(PROPAGATE_ITERATIONS):
        F_t_1 = F_t
        F_t = matrix.dot(F_t_1) + Y

        if math.sqrt(sp.linalg.norm(F_t_1 - F_t)) < PROPAGATE_EPSILON:
            break

    return F_t


def generate_propagate_data(network, interactors=None):
    matrix, genes = generate_similarity_matrix(network)
    num_genes = len(genes)
    gene_indexes = dict([(gene, index) for (index, gene) in enumerate(genes)])
    if interactors:
        gene_scores = {gene: propagate(
            [gene], matrix, gene_indexes, num_genes) for gene in interactors}
    else:
        gene_scores = {gene: propagate(
            [gene], matrix, gene_indexes, num_genes) for gene in genes}

    return matrix, num_genes, gene_indexes, gene_scores

## Data Loading

In [7]:
# Loading Datasets
g = read_network("H_sapiens.net")
# https://www.nature.com/articles/s41586-020-2286-9#Sec36
interactions = pd.read_csv("interactions.csv")
perm3 = pd.read_csv("perm3.csv")  # permeability after 3 Days
perm4 = pd.read_csv("perm4.csv")  # permeability after 4 Days

# %%
# propogate Network for all Genes
network_path = f"network_scores.pkl.gz"

if os.path.exists(network_path):
    print('loading propagated network from disk')
    network_scores = joblib.load(network_path)
    W, num_genes, gene_indexes, gene_scores = (
        network_scores["W"],
        network_scores["num_genes"],
        network_scores["gene_indexes"],
        network_scores["gene_scores"],
    )
else:
    print('start propagating network')
    W, num_genes, gene_indexes, gene_scores = generate_propagate_data(g)
    network_scores = {"W": W, "num_genes": num_genes, "gene_indexes": gene_indexes, "gene_scores": gene_scores}
    joblib.dump(network_scores, network_path)

target_index = [gene_indexes[i] for i in target if i in gene_indexes]

# Network stats
g_nodes, g_degrees = zip(*g.degree())
fig = px.histogram(x=g_degrees, nbins=1000)
fig.show()

loading propagated network from disk


In [ ]:
# mapping to entrez id
xli = interactions["PreyGene"].unique().tolist()
out = pd.DataFrame(mg.querymany(xli, scopes="symbol", fields="entrezgene", species="human"))
interactions = pd.merge(interactions, out[["query", "entrezgene"]], left_on="PreyGene", right_on="query")
interactions["entrezgene"] = interactions["entrezgene"].astype(int)

In [11]:
random_networks_path = f"random_networks_score.pkl.gz"
E = g.number_of_edges()
Q = 10

inter_genes = list(interactions["entrezgene"].unique())
random_networks = {}
if os.path.exists(random_networks_path):
  print('loading random networks from disk')
  random_networks = joblib.load(random_networks_path)
else:
  for i in range(100):
      H = g.copy()
      # rand_g, swaps = randomize_by_edge_swaps(g, 10)
      nx.swap.double_edge_swap(H, nswap=Q*E, max_tries=Q*E*2)
      W_temp, num_genes_temp, gene_indexes_temp, gene_scores_temp = generate_propagate_data(H, inter_genes)
      random_networks[i] = gene_scores_temp
      print(f"network {i} generated")
  random_networks_path = f"random_networks_score.pkl.gz"
  joblib.dump(random_networks, random_networks_path)

loading random networks from disk


In [12]:
# grouping count
interaction_count = interactions.groupby("viral", as_index=False).count()
interaction_count["viral"] = interaction_count.apply(lambda row: row["viral"].lower(), axis=1)

# %%
# lower case the protiens names
perm3["Viral Protein SARS-Cov-2"] = perm3.apply(lambda row: row["Viral Protein SARS-Cov-2"].lower(), axis=1)
perm4["Viral Protein SARS-Cov-2"] = perm4.apply(lambda row: row["Viral Protein SARS-Cov-2"].lower(), axis=1)

# join permeabilty and interactions
corr_data = interaction_count.merge(perm3, left_on="viral", right_on="Viral Protein SARS-Cov-2")
corr_data = corr_data.merge(perm4, left_on="viral", right_on="Viral Protein SARS-Cov-2")

ongoing_data = pd.DataFrame(columns=['viral', 'interactions_count', 'perm_3_days'])
ongoing_data['viral'] = corr_data['viral']
ongoing_data['interactions_count'] = corr_data['Preys']
ongoing_data['perm_3_days'] = corr_data['Permeability Value (3 days)']
ongoing_data['perm_4_days'] = corr_data['Permeability Value (4 days)']
del(corr_data)

In [ ]:
# calculate score by target random interactions
random_by_interactions = {}
for tar_id, name in zip(target, target_names):
    matrix = []
    for index, row in ongoing_data.iterrows():
        runs = []
        # calculate the score of viral gene
        sources = interactions[interactions["viral"].str.lower() == row["viral"]]["entrezgene"].to_list()
        score = sum([v[gene_indexes[tar_id]] for k, v in gene_scores.items() if k in sources]) 
        runs.append(score)
        # generate 100 random scores
        for i in range(100):
            random_sources = random.sample(population=list(g.nodes), k=len(sources))
            score = sum([v[gene_indexes[tar_id]] for k, v in gene_scores.items() if k in random_sources]) 
            runs.append(score)
        matrix.append(runs)
    random_by_interactions[name] = np.matrix(matrix)

random_by_interactions_path = f"random_by_interactions.pkl.gz"
joblib.dump(random_by_interactions, random_by_interactions_path)

# calculate score by target Random Networks
random_by_netwroks= {}
for tar_id, name in zip(target, target_names):
    matrix = []
    for index, row in ongoing_data.iterrows():
        runs = []
        # calculate the score of viral gene
        sources = interactions[interactions["viral"].str.lower() == row["viral"]]["entrezgene"].to_list()
        score = sum([v[gene_indexes[tar_id]] for k, v in gene_scores.items() if k in sources])
        runs.append(score)
        # generate 100 random scores by 100 random networks
        for net, prop in random_networks.items():
            score = sum([v[gene_indexes[tar_id]] for k, v in prop.items() if k in sources])
            runs.append(score)
        matrix.append(runs)
    random_by_netwroks[name] = np.matrix(matrix)
    ongoing_data[name + "_score"] = target_scores[name][:,0]

random_by_netwroks_path = f"random_by_netwroks.pkl.gz"
joblib.dump(random_by_netwroks, random_by_netwroks_path)
ongoing_data.to_csv('ongoing_data.csv',index=False)
# target_pvalues = {}
# for tar_id, matrix in target_scores.items():
#   correlations = []
#   for column in matrix.T:
#     inverse_perm= [1/i for i in ongoing_data["perm_3_days"]]
#     correlations.append(round(sp.stats.pearsonr(column.tolist()[0], inverse_perm)[0], 4))
#   pvalue = (102 - sp.stats.rankdata(correlations, method="ordinal")[0]) / 101
#   target_pvalues[tar_id] = {'correlation':correlations[0], 'p_value':pvalue}
# {k:v['correlation'] for k,v in target_pvalues.items()}

## Quick Load

In [5]:
from sklearn.cross_decomposition import CCA
random_by_netwroks_path = f"random_by_netwroks.pkl.gz"
random_by_interactions_path = f"random_by_interactions.pkl.gz"

random_by_netwroks = joblib.load(random_by_netwroks_path)
random_by_interactions = joblib.load(random_by_interactions_path)
ongoing_data = pd.read_csv("ongoing_data.csv")

In [6]:
def calc_pvalue(data, by_vascular = True):
  p_values = pd.DataFrame()
  scores = pd.DataFrame()    
  if by_vascular:
    for tar_name, matrix in data.items():
      p_values[tar_name + "_pvalue"] = ((101 - sp.stats.rankdata(matrix, method="ordinal",axis=1)) / 101)[:,0]
      scores[tar_name + "_score"] = matrix[:,0].A1
  else:
    sum_matrix = sum(data.values())
    p_values["pvalue_of_sum"] = ((101 - sp.stats.rankdata(sum_matrix, method="ordinal",axis=1)) / 101)[:,0]
    scores["score_of_sum"] = sum_matrix[:,0].A1
  return p_values, scores

In [8]:
p_values, scores = calc_pvalue(random_by_interactions)
Y = ongoing_data[['perm_3_days','perm_4_days']]

In [13]:
#random nieghbours 
p_values, scores = calc_pvalue(random_by_interactions)
Y = ongoing_data[['perm_3_days','perm_4_days']]
cca = CCA(n_components=1)
p_values_r, Y_r = cca.fit_transform(p_values, Y) 
print('P-value random neighbours: \n',np.corrcoef(p_values_r.T, Y_r.T))

P-value random neighbours: 
 [[1.         0.75393226]
 [0.75393226 1.        ]]


In [15]:
#scores
cca = CCA(n_components=1)
scores_r, Y_r = cca.fit_transform(scores, Y) 
print('absolute scores: \n',np.corrcoef(scores_r.T, Y_r.T))

absolute scores: 
 [[1.         0.77283989]
 [0.77283989 1.        ]]


In [11]:
# random networks
p_values, scores = calc_pvalue(random_by_netwroks)
Y = ongoing_data[['perm_3_days','perm_4_days']]
cca = CCA(n_components=1)
p_values_r, Y_r = cca.fit_transform(p_values, Y) 
print('P-value random networks: \n',np.corrcoef(p_values_r.T, Y_r.T))

P-value random networks: 
 [[1.         0.72991941]
 [0.72991941 1.        ]]


In [12]:
#average score
cca = CCA(n_components=1)
scores_r, Y_r = cca.fit_transform(scores.div(ongoing_data.interactions_count,axis=0), Y) 
print('average score: \n',np.corrcoef(scores_r.T, Y_r.T))

average score: 
 [[1.         0.86507342]
 [0.86507342 1.        ]]


In [13]:
{name:round(w,4) for name,w in zip(list(scores.columns),list(cca.x_weights_[:,0]))}

{'Cadherin-2_score': 0.1511,
 'Cadherin-3_score': -0.1354,
 'Cadherin-4_score': -0.1262,
 'Cadherin-5_score': -0.4801,
 'Catenin delta 1_score': 0.4059,
 'Cateninβ  _score': 0.5876,
 'Claudin-5_score': 0.2187,
 'Occludin_score': -0.1224,
 'ZO-1_score': 0.0293,
 'ZO-2_score': -0.2779,
 'ZO-3_score': 0.0422,
 'α Catenin _score': -0.2444}

In [14]:
{name:round(w,4) for name,w in zip(list(Y.columns),list(cca.y_weights_[:,0]))}

{'perm_3_days': 0.99, 'perm_4_days': -0.141}

In [48]:
correlations = []
for i in range(101):
  temp_scores = pd.DataFrame()
  for tar_name, matrix in random_by_netwroks.items():
    temp_scores[tar_name] = matrix[:,i].A1
  cca = CCA(n_components=1)
  Y = ongoing_data[['perm_3_days','perm_4_days']]
  scores_r, Y_r = cca.fit_transform(temp_scores.div(ongoing_data.interactions_count,axis=0), Y) 
  correlations.append(np.corrcoef(scores_r.T, Y_r.T)[0,1])


In [49]:
((101 - sp.stats.rankdata(correlations, method="ordinal")) / 101)[0]

0.039603960396039604

In [50]:
correlations

[0.8650734234542395,
 0.6266271620102581,
 0.5482591755589029,
 0.5866075330550836,
 0.7978522245203361,
 0.6218667187820199,
 0.7452340277321482,
 0.760915648773122,
 0.7966604448954459,
 0.8491032392867038,
 0.7244581005137485,
 0.743058014485218,
 0.7808877145492072,
 0.8435443093623304,
 0.7988252092767147,
 0.6805006134830665,
 0.7239320363814549,
 0.747691335228687,
 0.7461987842116137,
 0.8146463908449879,
 0.755587730958642,
 0.7535508106307346,
 0.7781406265453055,
 0.5862820401353163,
 0.832675636439666,
 0.8879167057266132,
 0.6093518774210006,
 0.7304678440483897,
 0.6594612004818008,
 0.7040213954606668,
 0.6192781972416553,
 0.8343428125570763,
 0.7578587318326996,
 0.8245190751421744,
 0.8147820621983785,
 0.5943247943153205,
 0.8763572488384014,
 0.6580888413414179,
 0.6846265993064794,
 0.6919938095243936,
 0.797667871752722,
 0.6534327520235692,
 0.7491412571521988,
 0.9105329984211132,
 0.6491397672506469,
 0.682910430899477,
 0.7767566235198571,
 0.7220378088947496,

In [87]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=True, with_std=True)
# X_sc = sc.fit_transform(scores)
# Y_sc = sc.fit_transform(p_values)